---
- name: Install Docker
  block:
    - name: Add universe
      apt_repository:
        repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
        state: present
    
    - name: Add additional package 
      apt:
        name:
          - apt-transport-https
          - ca-certificates      
          - curl
          - gnupg
          - lsb-release
        update-cache: yes
        cache_valid_time: 86400

    - name: Add key of Docker
      apt_key:
        url:  https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Install stable repository
      apt_repository:
        repo: >
          deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
          https://download.docker.com/linux/ubuntu
          {{ ansible_distribution_release }} stable
        state: present  
        update_cache: yes
        filename: docker
    
    - name: Install Docker-ce
      apt:
        name: docker-ce 
        update-cache: yes

    - name: Check Docker Install
      service:
        name: docker
        state: restarted
        enabled: yes
  become: yes 

- name: Install Docker-Compose
  block:
    - name: Get last version Docker-Compose
      uri:
        url: https://api.github.com/repos/docker/compose/releases/latest 
        body_format: json
      register: page

    - name: Install Docker-Compose
      get_url: 
        url: "https://github.com/docker/compose/releases/download/{{ page.json.tag_name }}/docker-compose-Linux-x86_64"
        dest: /usr/local/bin/docker-compose 
        mode: 0755
  become: yes

- name: Install PIP for Docker/Docker-Compose
  block:
    - name: PIP Docker
      pip:
        name: docker

    - name: PIP Docker-Compose
      pip:
        name: docker-compose
  become: yes
    
# - name: Finish Install 
#   block:
#     - name: Add user to group docker
#       user:
#         name: "{{ ansible_user }}"
#         append: yes
#         groups: docker
#     - name: restart server      
#       # shell: reboot
#       # async: 1000
#       # poll: 0
#       reboot:
#   become: yes