name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
 
    - name: Dockerize
      if: success()
      uses: manusa/actions-publish-docker@v1.1.2
      with:
        name: organization/image_name
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: docker build . --file Dockerfile --tag dragonkoc/test_it:$(date +%s)
